# flavor possible values:   "bianca_72x1"   "bianca_36x2"   "ariel_36x2"
flavor : "bianca_72x1"
sysname : "LuZhu-GB300-part2"
# Keep descending order of the tray indexes to mimic the physical ordering
# Use ZERO-based indexing to match the physical indexing
switches:
  - tray_index: 8
    ip_address: "192.168.2.69"
    username: "admin"
    password: "Admin1@admin"
    ssh_key: null
  - tray_index: 7
    ip_address: "192.168.2.68"
    username: "admin"
    password: "Admin1@admin"
    ssh_key: null
  - tray_index: 6
    ip_address: "192.168.2.67"
    username: "admin"
    password: "Admin1@admin"
    ssh_key: null
  - tray_index: 5
    ip_address: "192.168.2.66"
    username: "admin"
    password: "Admin1@admin"
    ssh_key: null
  - tray_index: 4
    ip_address: "192.168.2.65"
    username: "admin"
    password: "Admin1@admin"
    ssh_key: null
  - tray_index: 3
    ip_address: "192.168.2.64"
    username: "admin"
    password: "Admin1@admin"
    ssh_key: null
  - tray_index: 2
    ip_address: "192.168.2.63"
    username: "admin"
    password: "Admin1@admin"
    ssh_key: null
  - tray_index: 1
    ip_address: "192.168.2.62"
    username: "admin"
    password: "Admin1@admin"
    ssh_key: null
  - tray_index: 0
    ip_address: "192.168.2.61"
    username: "admin"
    password: "Admin1@admin"
    ssh_key: null
